# Generated by Django 4.2.6 on 2023-10-30 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=100)),
                ('balance', models.IntegerField(default=0)),
                ('donat', models.IntegerField(default=0)),
                ('legil', models.CharField(choices=[('Yuridik', 'Yuridik'), ('Jismoniy', 'Jismoniy')], max_length=40)),
                ('status', models.CharField(choices=[('Yangi', 'Yangi'), ('Moderatsiya', 'Moderatsiya'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], default='Yangi', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('statuc', models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr')], max_length=20)),
                ('contract', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('universitet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.universitet')),
            ],
        ),
        migrations.CreateModel(
            name='Donat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donator', to='app.donator')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app.student')),
            ],
        ),
    ]
